name: jubla
description: A new Flutter project.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.0
  flutter_screenutil: 4.0.3+1
  shared_preferences: 0.5.12
  font_awesome_flutter: 8.11.0
  flutter_bloc: 6.1.1
  dartz: 0.9.2
  get_it: 5.0.6
  freezed_annotation: 0.12.0
  flutter_spinkit: 4.1.2
  path_provider: 1.6.27
  camera: 0.7.0+2
  intl: 0.16.0
  auto_route: 0.6.9
  equatable: 1.2.5
  dio: 3.0.10
  data_connection_checker: 0.3.4
  fluttertoast: 7.1.8
  flutter_bounce: 1.0.8
  pull_to_refresh: 1.6.4
  image_picker: 0.6.7+22
  cached_network_image: 2.5.1
  email_validator: 1.0.6
  qr_code_scanner: 0.3.5
  flutter_launcher_icons: 0.8.1
  permission_handler: 5.1.0+2
  app_settings: 4.0.4
  uuid: 2.2.2
  qr_flutter: 3.2.0
  firebase_core: ^0.7.0
  cloud_firestore: ^0.16.0+1
  timeago: 2.0.30

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: 1.11.1
  freezed: 0.12.7
  auto_route_generator: 0.6.10


flutter_icons:
  #  image_path: "assets/images/icon-128x128.png"
  image_path_android: "assets/images/jubla.png"
  image_path_ios: "assets/images/jubla.png"
  android: true # can specify file name here e.g. "ic_launcher"
  ios: true # can specify file name here e.g. "My-Launcher-Icon"
  adaptive_icon_background: "assets/images/jubla.png" # only available for Android 8.0 devices and above
  adaptive_icon_foreground: "assets/images/jubla.png" # only available for Android 8.0 devices and above


flutter:
  uses-material-design: true
  assets:
  - assets/images/

  fonts:
    - family: vb
      fonts:
        - asset: assets/fonts/visB.otf
    
    - family: vr
      fonts:
        - asset: assets/fonts/visR.otf